name: Build
on:
  push:
    branches:
      - test
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: coursier/cache-action@v6
      - uses: olafurpg/setup-scala@v12

      - name: Run fast/full-opt
        run: |
          sbt {webapp,lambda}/{fast,full}OptJS/webpack

      - uses: hashicorp/setup-terraform@v1
      - name: Validate Terraform
        run: |
          cd terraform
          terraform init
          terraform validate

      # - name: Debug over SSH (tmate)
      #   # if: ${{ failure() }}
      #   uses: mxschmitt/action-tmate@v3
      #   with:
      #     limit-access-to-actor: true
